{{- if .Values.istio.enabled }}
{{- if .Values.istio.gateway.create }}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Values.istio.gateway.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.fullnameOverride }}
    environment: {{ .Values.environment }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: {{ .Values.istio.gateway.port }}
      name: http
      protocol: {{ .Values.istio.gateway.protocol }}
    hosts:
    {{- range .Values.istio.gateway.hosts }}
    - {{ . | quote }}
    {{- end }}
{{- end }}
{{- end }}