{{- if .Values.istio.enabled }}
{{- if .Values.istio.virtualService.create }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Values.istio.virtualService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "java-app.labels" . | nindent 4 }}
spec:
  hosts:
  {{- range .Values.istio.virtualService.hosts }}
  - {{ . | quote }}
  {{- end }}
  gateways:
  - {{ .Values.istio.gateway.name }}
  http:
  {{- range .Values.istio.virtualService.http }}
  - match:
    {{- range .match }}
    - uri:
        prefix: {{ .uri.prefix | quote }}
    {{- end }}
    route:
    {{- range .route }}
    - destination:
        host: {{ .destination.host }}
        port:
          number: {{ .destination.port.number }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}