# Clean values - no imagePullSecrets needed
replicaCount: 2

image:
  repository: 369528189607.dkr.ecr.eu-west-1.amazonaws.com/devsecops/java-app
  pullPolicy: Always
  tag: "latest"

service:
  type: LoadBalancer
  name: java-app
  port: 8080
  targetPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Health checks
healthCheck:
  enabled: true
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10

# Application configuration
config:
  springProfile: "default"
  logLevel: "INFO"
  javaOpts: "-Xmx256m"

# Environment-specific settings
environment: "development"