replicaCount: 2

image:
  repository: 369528189607.dkr.ecr.eu-west-1.amazonaws.com/devsecops/java-app
  tag: latest
  pullPolicy: Always

containerPort: 8080


fullnameOverride: java-app

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

healthCheck:
  enabled: true
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

config:
  springProfile: prod
  javaOpts: "-Xms512m -Xmx512m"

environment: prod
