replicaCount: 2

image:
  repository: 369528189607.dkr.ecr.eu-west-1.amazonaws.com/devsecops/java-app
  tag: latest
  pullPolicy: Always

containerPort: 8080

fullnameOverride: java-app

# Istio-ready service configuration
service:
  type: ClusterIP  # Changed from LoadBalancer to ClusterIP for Istio
  port: 80
  targetPort: 8080

# Istio Gateway and VirtualService configuration
istio:
  enabled: true
  gateway:
    create: true
    name: java-app-gateway
    hosts:
      - "*"  # Change to your domain in production, e.g., "myapp.company.com"
    port: 80
    protocol: HTTP
  virtualService:
    create: true
    name: java-app-vs
    hosts:
      - "*"
    http:
      - match:
          - uri:
              prefix: /
        route:
          - destination:
              host: java-app
              port:
                number: 80

healthCheck:
  enabled: true
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

securityContext:
  runAsUser: 100
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - NET_RAW

volumeMounts:
  - name: vol
    mountPath: /tmp

volumes:
  - name: vol
    emptyDir: {}

config:
  springProfile: prod
  javaOpts: "-Xms512m -Xmx512m"

environment: prod