name: DAST - ZAP API Scan

on: [push]

permissions:
  contents: read
  issues: write


jobs:
  zap_scan:
    name: DAST - ZAP API Scan
    runs-on: ubuntu-latest
    steps:
      - name: ZAP API Scan
        uses: zaproxy/action-api-scan@v0.9.0
        with:
          target: 'http://a01c5c313c42f497d82b3d6f95640868-541966697.eu-west-1.elb.amazonaws.com'
